language: cpp

branches:
  only: 
  - master
  
before_install:
- sudo add-apt-repository "deb http://ppa.launchpad.net/djcj/vapoursynth/ubuntu trusty main" -y
- sudo add-apt-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main" -y
- sudo apt-get update -qq
- sudo apt-get install --allow-unauthenticated g++-5
- sudo mv /etc/default/rcS /etc/default/rcS.backup
  
install:
- sudo apt-get install opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev 
- sudo apt-get install --allow-unauthenticated libvapoursynth-dev 

script: 
- ./configure --cxx=g++-5 --install=/usr/lib/x86_64-linux-gnu/vapoursynth && make && sudo make install

notifications:
  email: false
