language: cpp

branches:
  only: 
  - master
  
before_install:
- sudo add-apt-repository "deb http://ppa.launchpad.net/djcj/vapoursynth/ubuntu trusty main" -y
- sudo add-apt-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main" -y
- sudo apt-get update -qq
- sudo apt-get install --allow-unauthenticated g++-5
- sudo mv /etc/default/rcS /etc/default/rcS.backup
  
install:
- sudo apt-get install opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev ninja
- sudo apt-get install --allow-unauthenticated libvapoursynth-dev 
- sudo pip3 install meson

script: 
- mkdir build && cd build && meson .. && ninja && ninja install

notifications:
  email: false
