language: cpp

branches:
  only: 
  - master
  
before_install:
- sudo add-apt-repository "deb http://ppa.launchpad.net/djcj/vapoursynth/ubuntu trusty main" -y
- sudo apt-get update
- sudo mv /etc/default/rcS /etc/default/rcS.backup
  
install:
- sudo apt-get install opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev 
- sudo apt-get install --allow-unauthenticated libvapoursynth-dev 

script: 
- ./configure --cxx=g++-4.8 --install=/usr/lib/x86_64-linux-gnu/vapoursynth && make && sudo make install

notifications:
  email:
    - on_success: never
    - on_failure: never
