language: cpp

branches:
  only: 
  - master
  
before_install:
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty main universe restricted multiverse" -y
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-security main universe restricted multiverse" -y
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-updates main universe restricted multiverse" -y
- sudo add-apt-repository "deb http://ppa.launchpad.net/djcj/vapoursynth/ubuntu trusty main" -y
- sudo apt-get update -qq
- sudo apt-get install -qq -t trusty gcc-4.8 g++-4.8 make pkg-config
- sudo mv /etc/default/rcS /etc/default/rcS.backup
- export CC="gcc-4.8" CXX="g++-4.8" 
  
install:
- sudo apt-get install -qq -t trusty opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev 
- sudo apt-get install -qq -t trusty libvapoursynth libvapoursynth-dev libpango-1.0-0 libpangocairo-1.0-0

script: 
- ./configure --install=/usr/lib/x86_64-linux-gnu/vapoursynth --cxx=$CXX && make && sudo make install

notifications:
  email:
    - on_success: never
    - on_failure: never
