sudo: false

os:
  - linux

language: 
  - cpp

services:
  - docker
  
branches:
  only: 
  - master
  
before_install:
  - docker pull 4re/KNLMeansCL:bionic

install: 
  - docker exec -t ubuntu-bionic bash -c "
  apt-get update -qq;
  apt-get install meson ocl-icd-opencl-dev software-properties-common -y;
  add-apt-repository ppa:djcj/vapoursynth -y;
  apt-get update -qq;
  apt-get install libvapoursynth-dev -y"
