language: cpp

before_install:
        - sudo add-apt-repository ppa:djcj/vapoursynth -y
        - sudo apt-get update -qq
        - sudo apt-get install -y --install-suggests pkg-config  vapoursynth opencl-headers

install: true

script: 
         - ./configure
         - make
         - sudo make install

