language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential yasm git libavcodec-dev libswscale-dev libass-dev python3-pip python3-dev
  - pip3 install cython
  - git clone https://github.com/vapoursynth/vapoursynth.git

before_script:
  - chmod +x configure

script: ./configure

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux
