language: cpp

branches:
  only: 
  - master
  
before_install:
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial main universe" -y
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial-security main universe" -y
- sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial-updates main universe" -y
- sudo add-apt-repository "deb http://ppa.launchpad.net/djcj/vapoursynth/ubuntu xenial main" -y
- sudo apt-get update -qq
- sudo apt-get install -qq -t xenial g++-5 make pkg-config
- sudo mv /etc/default/rcS /etc/default/rcS.backup
  
install:
- sudo apt-get install -qq -t xenial opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev 
- sudo apt-get install -qq -t xenial libvapoursynth libvapoursynth-dev libpango-1.0-0 libpangocairo-1.0-0

script: 
- ./configure --cxx=g++-5 --install=/usr/lib/x86_64-linux-gnu/vapoursynth && make && sudo make install

notifications:
  email:
    - on_success: never
    - on_failure: never
